[package]
name = "cibo"
version = "0.1.0"
authors = ["hawkingrei <hawking.rei@gmail.com>"]

[dependencies]
clippy = { version = "*", optional = true }
crossbeam-epoch = "0.4.0"
crossbeam-utils = "0.2.2"
crossbeam-deque = "0.3.0"
libc = "0.2"

[dev-dependencies]
rand = "0.4"